// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestionale_Drian.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422100147_CampiPreventivo")]
    partial class CampiPreventivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Articolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantitaInMagazzino")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Articoli");
                });

            modelBuilder.Entity("Associato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cellulare")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDiNascita")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTessera")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Associati");
                });

            modelBuilder.Entity("AssociatoProgetto", b =>
                {
                    b.Property<int>("MembriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgettiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MembriId", "ProgettiId");

                    b.HasIndex("ProgettiId");

                    b.ToTable("AssociatoProgetto");
                });

            modelBuilder.Entity("Movimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticoloId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Causale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantita")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArticoloId");

                    b.ToTable("Movimenti");
                });

            modelBuilder.Entity("Progetto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataConsegna")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<string>("GiorniConsegna")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompletato")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConsegnato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreventivoPdfPath")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrezzoTotale")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ScontoPercentuale")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipologiaConsegna")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Progetti");
                });

            modelBuilder.Entity("VocePreventivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgettoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantita")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProgettoId");

                    b.ToTable("VocePreventivo");
                });

            modelBuilder.Entity("AssociatoProgetto", b =>
                {
                    b.HasOne("Associato", null)
                        .WithMany()
                        .HasForeignKey("MembriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Progetto", null)
                        .WithMany()
                        .HasForeignKey("ProgettiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Movimento", b =>
                {
                    b.HasOne("Articolo", "Articolo")
                        .WithMany("Movimenti")
                        .HasForeignKey("ArticoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articolo");
                });

            modelBuilder.Entity("VocePreventivo", b =>
                {
                    b.HasOne("Progetto", null)
                        .WithMany("VociPreventivo")
                        .HasForeignKey("ProgettoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Articolo", b =>
                {
                    b.Navigation("Movimenti");
                });

            modelBuilder.Entity("Progetto", b =>
                {
                    b.Navigation("VociPreventivo");
                });
#pragma warning restore 612, 618
        }
    }
}
